# this goes inside _config.yml. Change as required
navigation:
        - text: Home
          url: /index.html
        - text: Research
          url: /research.html
        - text: About me
          url: /about.html
