# this goes inside _config.yml. Change as required
navigation:
        - text: Home
          url: /index.html
        - text: Research
          url: /research.html
        - text: Service
          url: /service.html
        - text: Awards
          url: /awards.html
        - text: About Me
          url: /about.html

baseurl: "https://www.cc.gatech.edu/~xzhang36"
